### ISSUE TITLE
Kobun fails to greet distinguished members with personalized greetings.

### ISSUE THREAD

**Issue by lucianRf** [rfw/kochira#36]
Consider the following

    Arty has joined #channel 
    <Kobun> Mmm whatchu saaaaaaaay? It's Artholobae!

Isn't that neat? No?

**Comment by rfw** [comment]
no

**Comment by rfw** [comment]
jk ok

**Comment by lucianRf** [comment]
maybe !setintro as the command?

**Comment by rfw** [comment]
command is !setgreet/!ungreet
